config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  root 'home#top'
  get 'home/about' => 'home#about'
  devise_for :users
  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加
    get :followers, on: :member # 追加
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  attachment :profile_image, destroy: false
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, presence: true, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
    @user = current_user
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user.id), notice: "successfully updated user!"
  	else
  		render :edit
  	end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
  def correct_user
  	user = User.find(params[:id])
    if user != current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, size: '100x100', fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
			<th>follows</th>
			<th><%= link_to user.followings.count, follows_user_path(user.id) %></th>
		</tr>
		<tr>
			<th>followers</th>
			<th><%= link_to user.followers.count, followers_user_path(user.id) %></th>
		</tr>
</table>

<% if user == current_user %>
	<div class="row">
		<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	</div>
<% end %>

<% if current_user != user %>
    <% if user.followed_by?(current_user) %>
        <%=link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-danger" %>
    <% else %>
        <%=link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
    <% end %>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/followers.html.erb
<div class="container">
  <h1>Follower Users</h1>

  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
      </tr>
    <thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, size: "50x50", fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td><%= "フォロー数: #{user.followings.count}" %></td>
          <td><%= "フォロワー数: #{user.followers.count}" %></td>
          <% if current_user != user %>
            <% if user.followed_by?(current_user) %>
              <td><%= link_to "フォロー済み", user_relationships_path(user.id), method: :delete %><td>
            <% else %>
              <td><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
            <% end %>
          <% end %>
          <td><%= link_to "show", user_path(user.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/follows.html.erb
<div class="container">
  <h1>Follow Users</h1>

  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
      </tr>
    <thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, size: "50x50", fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td><%= "フォロー数: #{user.followings.count}" %></td>
          <td><%= "フォロワー数: #{user.followers.count}" %></td>
          <% if current_user != user %>
            <% if user.followed_by?(current_user) %>
              <td><%= link_to "フォロー済み", user_relationships_path(user.id), method: :delete %><td>
            <% else %>
              <td><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
            <% end %>
          <% end %>
          <td><%= link_to "show", user_path(user.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/index.html.erb
<div class="row" >
  <div class="col-xs-3">
	<h2>User info</h2>
	<%= render 'users/profile', user: @user %>　
	<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->
	<h2>New book</h2>
	<%= render 'books/newform', book: @book %>
  </div>

  <div class="col-xs-9" >
	<h2>Users</h2>
	<!--users一覧 -->
	<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			<% @users.each do |user| %>
			<tr>
				<td><%= attachment_image_tag(user, :profile_image, size: '50x50', fallback: "no-image-mini.jpg") %></td>
				<td><%= user.name%></td>
				<td><%= "フォロー数: #{user.followings.count}" %></td>
				<td><%= "フォロワー数: #{user.followers.count}" %></td>
				<% if current_user != user %>
					<% if user.followed_by?(current_user) %>
						<td><%=link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></td>
					<% else %>
						<td><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
					<% end %>
				<% else %>
					<td></td>
				<% end %>
				<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<!--users一覧 -->
  </div>
</div>

app/views/users/show.html.erb
<div class="row" >
  <div class="col-xs-3">
	<h2>User info</h2>
	<%= render 'users/profile', user: @user %>
	<!--同コントローラーのviewで表示ならusersは省略可 -->
	<h2>New book</h2>
	<%= render 'books/newform', book: @book %>
  </div>

  <div class="col-xs-9" >
	<h2>Books</h2>
	<!--books一覧 -->
	<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th></th>
				<th>Title</th>
				<th>Opinion</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @books.each do |book| %>
			<tr>
				<td>
					<%= link_to (book.user) do %>
					<%= attachment_image_tag(book.user, :profile_image, size: '50x50', fallback: "no-image-mini.jpg") %>
					<% end %>
				</td>
				<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
				<td><%= book.body %></td>
				<td><%= link_to "コメント数: #{book.book_comments.count}", book_path(book.id) %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<!--books一覧 -->
  </div>
</div>