config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  root 'home#top'
  get 'home/about' => 'home#about'
  devise_for :users
  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加
    get :followers, on: :member # 追加
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
	  favorites.where(user_id: user.id).exists?
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def show
  	@book = Book.find(params[:id])
    @user = @book.user
    @books = Book.new
    @book_comment = BookComment.new
  end

  def index
    @user = current_user
    @book = Book.new
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
  end

  def create
    @user = current_user
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
  	@book.user_id = current_user.id
    if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
  def correct_user
    book = Book.find(params[:id])
    if book.user_id != current_user.id
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/_post.html.erb
<td>
    <%= link_to (book.user) do %>
    <%= attachment_image_tag(book.user, :profile_image, size: '50x50', fallback: "no-image-mini.jpg") %><br>
    <%= book.user.name %>
    <% end %>
</td>
<td><%= link_to book.title, book %></td>
<td><%= book.body %></td>
<td>
    <% if book.favorited_by?(current_user) %>
        <%= link_to book_favorites_path(book.id), method: :delete, remote: true do %>
            <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
            <%= book.favorites.count %>
        <% end %>
    <% else %>
        <%= link_to book_favorites_path(book.id), method: :post, remote: true do %>
            <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
            <%= book.favorites.count %>
        <% end %>
    <% end %>
</td>
<td><p>コメント数: <%= book.book_comments.count %></p></td>

app/views/books/edit.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>

		<% if @book.errors.any? %>
			<h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3><!--エラーメッセ-->
			<ul>
				<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>

		<%= render "books/newform", book: @book %>
		<%= link_to "Show", @book, class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

    </div>
    <div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">

    <% if @book.errors.any? %>
		<h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3><!--エラーメッセ-->
		<ul>
			<% @book.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>

	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
					<tr id="post_area_<%= book.id %>">
						<%= render 'books/post', book: book %>
					</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @books %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table table-hover table-inverse">
			<tbody>
				<tr id="post_area_<%= @book.id %>">
					<%= render 'books/post', book: @book %>
					<% if @user.id == current_user.id %>
						<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
						<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
			</tbody>
		</table>
		<%= render 'book_comments/comments_area' %>
		<%= form_with(model: [@book, @book_comment], remote: true) do |f| %>
			<%= f.label "comment" %>
			<%= f.text_area :comment %>
			<%= f.submit "送信" %>
		<% end %>
	</div>
</div>